version: '2.1'
services:
    web:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "microsoft/webrgz-master"
        environment:
            SA_PASSWORD: "123"
            ACCEPT_EULA: "Y"

